version: "3.9"

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:v18.0.0
    container_name: gitlab-runner
    restart: unless-stopped

    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - gitlab_default

volumes:
  gitlab_runner_config:

networks:
  gitlab_default:
    external: true
