stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/user/app

test:
  stage: test
  image: node:20
  script:
    - npm install
    - npm test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add openssh
  script:
    - ssh root@MEU_SERVIDOR "
        docker pull $IMAGE_NAME &&
        docker compose up -d
      "